FROM petergrace/limbo
# Add your plugins with lines similar to these
ADD limbo/plugins/bing.py /app/limbo/plugins/
ADD limbo/plugins/my_new_plugin.py /app/limbo/plugins/
ADD limbo/plugins/my_other_new_plugin.py /app/limbo/plugins/
